### ISSUE TITLE
[Feature Request] GitHub Actions

### ISSUE THREAD

**Issue by luigi311** [truenas/truenas-build#16]
We could implement a GitHub action that will run the build process on pushes/pr using a prestine Debian image for CI purposes to validate that no changes have broken the build process. If you wish this is something I can implement and can be expanded if need be later. The action will be for CI and not CD so the images it builds will not be accessable but it is an option.

**Comment by kmoore134** [comment]
@luigi311 This would be super nice to see if any pending PR's will be breaking the builder. If you want to take a stab at it and give us a PR to review, be happy to take a look at it!

**Comment by luigi311** [comment]
Looks like github is reluctant to add debian as a virtual environment. https://github.com/actions/virtual-environments/issues/45
Are you guys ok with building in ubuntu or do you guys want me to create a docker file that uses debian as its image and build it in there?
Here is a successful run in ubuntu. https://github.com/luigi311/truenas-build/runs/777171094?check_suite_focus=true
Looks like it takes about an hr to run.

**Comment by luigi311** [comment]
Let me know if you want me to use docker or limit it to just PR and i can go ahead and make the change and then submit a PR for it.

**Comment by kmoore134** [comment]
I'm fine with it using Ubuntu as the build environment for the time being. Its probably good to have it working properly there anyway.
