### ISSUE TITLE
Installing in a VM fails

### ISSUE THREAD

**Issue by luigi311** [truenas/truenas-build#20]
Loading the TrueNAS-SCALE.iso into a VM fails to run the installer. It errors out saying /cdrom already exists, /dev/sr0 is already mounted on it which should be fine but then it errors out saying sbin/truenas-install does not exist. 

Build OS: Ubuntu 18.04.4 LTS

OS: Unraid
VM-system: KVM
XML: [kvm.zip](https://github.com/truenas/truenas-build/files/4794659/kvm.zip)

This is on a fresh build. Also looks like it keeps the same hostname as the system that built it.
![image](https://user-images.githubusercontent.com/4695527/84940368-f8932100-b09c-11ea-8c7f-8ff5aad2bbae.png)

**Comment by william-gr** [comment]
Maybe because that was built on Ubuntu, we have only tested on debian and doing install almost every day. Cant imagine why though.

**Comment by luigi311** [comment]
Let me load up a debian build env

**Comment by luigi311** [comment]
Creating the iso in debian does indeed fix the issue. Marking this issue as fixed. Do you want me to create a issue on building in ubuntu or should i not since you guys only officially support debian and not ubuntu?
