### ISSUE TITLE
Webgui does not load when updating via webgui

### ISSUE THREAD

**Issue by luigi311** [truenas/truenas-build#21]
Updating truenas via the webgui from TrueNAS-13.0-MASTER-20200617-140209 to TrueNAS-13.0-MASTER-20200617-172910 results in the webgui no longer loading when it restarts. On the console itself it does not even show the 
```
The web user interace is at :
http://
https://
```
information. Selecting option 9 to go into the shell and doing an ip addr show does show me an ip addr and navigating to it does not bring up the webgui. Exiting and going back to the console menu and selecting 1 to configure the network interface brings up an error 
```
ifconfig: option `-l' not recognized.
```
with no information on that section but exiting that section seems to fix the issue and gets the webgui working with the web user interface information appearing. I have reinstalled the 140209 and recreated the steps and it still occurs.
![image](https://user-images.githubusercontent.com/4695527/84957926-7d8c3380-b0b9-11ea-980b-bd375902663f.png)

**Comment by william-gr** [comment]
Please use https://jira.ixsystems.com/secure/Dashboard.jspa to issues.
