### ISSUE TITLE
Ip settings on the console do not work

### ISSUE THREAD

**Issue by rhmk** [truenas/truenas-build#23]
On the console /etc/netcli is started.  In line 87ff it reads:
 ```
87     def __iter__(self):
88         pipe = os.popen("/sbin/ifconfig -l")
89         self._NIClist = pipe.read().strip().split(' ')
```
ifconfig -l is BSD specific, hence this needs to be changed e.g. to the following to work in linux:
 ```
87     def __iter__(self):
88         pipe = os.popen("/bin/ls -1 /sys/class/net")
89         self._NIClist = pipe.read().strip().split('\n')
```
I don't know from which repository it comes, so I cannot post a patch. Please point me to the repository or fix it please.

Sorry

**Comment by william-gr** [comment]
https://github.com/freenas/freenas/pull/4992/files
