### ISSUE TITLE
Inconsistent disk references

### ISSUE THREAD

**Issue by theyetter** [truenas/truenas-build#36]
So in trying out truenas core, I came across an issue that might be the result of the switch to Debian from FreeBSD?  Disk references of the form sda, sdb, sdc, etc. are not consistent across reboots in linux.  If you change absolutely nothing, the disks will probably have the same device reference ids but it's not guaranteed.  And if you change something, such as adding an SAS controller with SAS drives attached after installing, your drive references can all change.  But it still refers to those origina references in truenas.  

An example:
When I installed, I had 4 sata drives: sda, sdb, sdc and sdd.  Truenas was installed on sdc and sdd.  I then put in an sas card with 2 drives attached.  Those new sas drives became sda and sdb, from the perspective of linux and old sda became new sdc, old sdb became new sdd, old sdc became new sde and old sdd became new sde.  However, the webgui interface still referred to the original drives for sda and sdb and had no acknowledgement of sde or sdf and still saw sdc and sdd as the truenas boot drives even though they were now sde and sdf in linux.  Because of this, I wasn't able to run any functions on any of the disks inside of the webgui.  This effectively rendered truenas unable to perform any functions.

If this is because of a difference between freebsd and linux (I have not used freebsd much so am not particularly familiar with how it handles such), it's worth considering keying off of the UUID rather than the drive device id reference as the UUID should remain consistent while the drive device id reference almost definitely won't over time.

**Comment by kmoore134** [comment]
Thanks for the response! This sounds like a bug that we're going to need to investigate further. Would you mind opening an issue up on https://jira.ixsystems.com so we can track it and get a fix merged?
