### ISSUE TITLE
Debootstrap not found with default install instructions

### ISSUE THREAD

**Issue by Ornias1993** [truenas/truenas-build#9]
Not a Bug with TrueNAS, but with the Github build instructions:

Using the build instructions on a plain debian 10 install (latest, downloaded, installed with basic settings (without gui), apt-get update, apt-get clean, apt-get install git), I got the warning that debootstrap couldn't be found.

It seems `/sbin` wasn't added to path on default debian install. Which was required for debootstrap to be detected. Might be worthwhile adding a note about.

**Comment by kmoore134** [comment]
Interesting, did you just have to add /sbin to your default PATH? I don't recall having to do that on my install here. We could always add PATH to the build scripts to work around it as well.

**Comment by Ornias1993** [comment]
@kmoore134 Yeah I also find it a bit strange, but it was truely a prestine install.

Original path after install and adding the dependencies:
`/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`

Running the following path export, solved the issue:
`export PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"`

On second look, it seems all sbins where not added to path originally.
LS showed debootstrap to reside at /sbin at least...

**Comment by Ornias1993** [comment]
Okey, I tested just running the old path (without sbin references) and adding /sbin to it:
`export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin"`

This solves the issue, while re-running using the original path makes the error appear again.:
`export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"`

**Comment by Ornias1993** [comment]
*Update*
Some additional research:
Debian seems to have to different default PATHS:
ENV_SUPATH
ENV_PATH

The first one (obviously) applies to the root user, so far so good and does contain sbin.
However: The path doesn't get loaded when going into root using su.

Simply put:
- Login to the machine using root
- `echo $PATH`
results in:
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

- Login to the machine using testuser
- `echo $PATH`
results in:
`/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`

- Login to the machine using testuser
- `su root`
- `echo $PATH`
results in:
`/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`


How to fix this?
1. Set path before execution
Or
2. Run the following after using `su root`:
`bash --login`

**Comment by Ornias1993** [comment]
Thanks for the fix, i'll continue checking out the great progress on this :)
